### ISSUE TITLE
Test payload issue

### ISSUE THREAD

**Issue by lunalik2** [noahc3/Homebrew-Guide#1]
About last month, there was a report of the test payload bricking a switch on Reiswitched. It definitely isn't common, but you should still take the precaution of giving a warning or removing the link. Besides that small issue, the guide is overall great, very helpful to newcomers :+1:.

**Comment by noahc3** [comment]
Thanks for letting me know. I'm gonna write my own test payload today since that one also has the blue screen issue which can confuse people.

**Comment by noahc3** [comment]
Guide now uses a custom test payload based on latest Atmosphere-NX.
