### ISSUE TITLE
Direct navigation to switch theme causes infinite redirect

### ISSUE THREAD

**Issue by snoozbuster** [noahc3/Homebrew-Guide#102]
As title says: Direct navigation to https://switch.homebrew.guide/switch-theme.html triggers an infinite redirect. Would be better to detect this case and redirect to the homepage. 

I don't see the actual redirect for the page (added by https://github.com/noahc3/Homebrew-Guide/commit/e936816e2e23be8ba004dc8d359e97f738a60a88) in the repo, so I assume it's part of a bit of nginx config not included here.

**Comment by noahc3** [comment]
Fixed, thanks.

Redirect is handled by a script in [_templates/layout.html](https://github.com/noahc3/Homebrew-Guide/blob/master/_templates/layout.html) since everything is hosted statically on Github Pages.
