### ISSUE TITLE
Update FAQ "Is it safe to update to the latest firmware version?"

### ISSUE THREAD

**Issue by Jeddunk** [noahc3/Homebrew-Guide#55]
https://switch.homebrew.guide/faq#is-it-safe-to-update-to-the-latest-firmware-version

It currently contains outdated information:

> As of writing, the latest firmware version is 9.1.0. It is currently completely safe to update as long as you are using Atmosphere v0.10.0+, Kosmos v15+ or a bundle from SDSetup downloaded after December 7th 2019.

**Comment by GGLinnk** [comment]
Fixed, issue should be closed.

**Comment by noahc3** [comment]
5409de1ca63367dd39d6ccb7b86fd227b7b5ca1a
