### ISSUE TITLE
Recommendation : Separate Homebrew-Guide into 3 repos (#28, #29)

### ISSUE THREAD

**Issue by GGLinnk** [noahc3/Homebrew-Guide#72]
So, what I suggest is to separate this repo into 3 repo: 
- Homebrew-Guide-Home: homebrew.guide
- Homebrew-Guide-Switch: switch.homebrew.guide
- Homebrew-Guide-WiiU: wiiu.homebrew.guide

So the Homebrew-Guide-Home will be the "nice landing page" (#29).
Homebrew-Guide-Switch and Homebrew-Guide-WiiU will be dedicated to each console (#28).

**Comment by tumGER** [comment]
Yes, that's what we're planning to do sooner or later.

**Comment by noahc3** [comment]
Duplicate #28, #29...
