### ISSUE TITLE
DNS usage details

### ISSUE THREAD

**Issue by muldos** [noahc3/Homebrew-Guide#75]
Hi, in this part : 

===
"Step 3: Blocking Updates & Telemetry with 90DNS
You can configure your WiFi settings to use a custom DNS server that blocks all connections to Nintendo servers (except the internet connection test server).

Doing this will make games unable to be played online, block eShop, game updates and system updates. If you are OK with this, follow these instructions:

Boot your Switch with or without CFW.

Open settings and go to the Internet tab

Configure a WiFi connection if you have not already done so

Select your Wifi network and pick Change Settings

Set DNS Settings to Manual

Set ‘Primary DNS’ to ‘163.172.141.219’

Set ‘Secondary DNS’ to ‘45.248.48.62’

Save and perform a connection test by connecting to the network. The connection test should pass.

===
I think the guide should mention when to switch dns.
As a first tie reader of the guide, it's unclear for me if DNS modification is a permanent thing, or if it should be done only before using CFW.
Does the console log every app launched and send this log back to nintendo when we restore dns to default settings ?
Thanks in advance for your clarification / explanations.
Kind regards,
David

**Comment by noahc3** [comment]
Added some info about when and how DNS should be used, and added a list of bannable offenses to the FAQ. Thanks!
