### ISSUE TITLE
Remove contradictory text about backups

### ISSUE THREAD

**Issue by grantlison** [noahc3/Homebrew-Guide#82]
The [Caffeine safety precautions](https://github.com/noahc3/Homebrew-Guide/blob/master/hacking/caffeine/safetyprecautions.rst) page uses the same header text as the other safety precaution pages, despite body text a few lines down stating the opposite Could cause somebody to get confused abot whether or not do backup.

> You are now able to run Hekate on your Nintendo Switch to launch the Atmosphere custom firmware. These next steps will make sure your being as careful as possible in regards to keeping your Switch from bricking and getting banned. _These steps are optional but highly recommended_
...
> **THIS STEP IS NOT OPTIONAL, ESPECIALLY FOR IPATCHED UNITS.**

**Comment by grantlison** [comment]
Additional problem: [The manual upgrade/downgrade with PC](https://github.com/noahc3/Homebrew-Guide/blob/master/usingcfw/manualchoiupgrade.rst) page refers to step 1.13 at several points in ways to fix a problem, despite step 1 ending at 1.12.

> Step 1: Preparing Files

    1. Make sure your SD card includes a basic Hekate/Atmosphere setup (such as the one installed when following this guide)
    2. Insert your SD card into your PC
    3. Go to switchtools.sshnuke.net
    4. Download the latest version of ChoiDujour (NOT ChoiDujourNX) by rajkosto
    5. Download the latest version of HacDiskMount by rajkosto
    6. Download the latest version of memloader by rajkosto
    7. Extract each downloaded .ZIP file to separate folders on your PC
    8. Copy your hactool keys.txt into the ChoiDujour folder
    9. Create a folder named "fw" inside of your ChoiDujour folder
    10. Extract the contents of your firmware .ZIP file to the newly created "fw" folder
    11. Go to www.balena.io/etcher/, download and install Etcher for your system
    12. In File Explorer, make sure Hidden Files are set to be shown
...
[(4.3)](https://github.com/noahc3/Homebrew-Guide/blob/master/usingcfw/manualchoiupgrade.rst#step-4-converting-firmware-files)
> If ChoiDujour says it cannot find firmware files or keys.txt, you likely put keys.txt or the firmware files in the wrong location. Try steps 1.9-**1.13** again.
...

[(5.9)](https://github.com/noahc3/Homebrew-Guide/blob/master/usingcfw/manualchoiupgrade.rst#step-5-transferring-boot0-to-your-switch)
> "BOOT0.BIN" MUST SHOW AS 1.57MB. "Linux UMS USB Device" MUST SHOW AS 4.19MB. If any of the sizes are incorrect, STOP! You cannot continue! Repeat steps 1.11-**1.13**, 4.1-4.4, and 5.3-5.9.
...

[(6.6)](https://github.com/noahc3/Homebrew-Guide/blob/master/usingcfw/manualchoiupgrade.rst#step-6-transferring-boot1-to-your-switch)
> "BOOT0.BIN" MUST SHOW AS 524.29KB. "Linux UMS USB Device" MUST SHOW AS 4.19MB. If any of the sizes are incorrect, STOP! You cannot continue! Repeat steps 1.11-**1.13**, 4.1-4.4, and 5.1-5.7.

**Comment by noahc3** [comment]
These issues are fixed, thank you!
