### ISSUE TITLE
Warnings - Nintendo bans

### ISSUE THREAD

**Issue by MilesTeg81** [noahc3/Homebrew-Guide#9]
(first page, before getting started) The paragraph about bans should mention  how bans work:

Any system changes AND then accessing internet without precautions might lead to a ban.

**Comment by tumGER** [comment]
`<li>Nintendo is taking no chances with the Nintendo Switch. <b>Permanent console bans can and often do happen.</b> This guide will take many precautions to avoid getting banned, but this site assumes no responsibility if your system is banned.</li>`

I think that warning is honestly fine - Besides, we recommend a DNS throughout the guide so removing the DNS is their own fault
