### ISSUE TITLE
No mention of new versions

### ISSUE THREAD

**Issue by Oscie57** [noahc3/Homebrew-Guide#93]
The guide literally makes it look like you have to hardmod the system to be able to mod anything above 4.1.0 which is completely false

**Comment by HookedBehemoth** [comment]
![image](https://user-images.githubusercontent.com/22580720/104830202-c50bb580-587c-11eb-8712-70670763d8c0.png)
What are you talking about?

ALL VERSIONS seems pretty clear to me.

**Comment by Oscie57** [comment]
It says on fusee-gelee that its hardmod, which is what i said. "you have to hardmod the system to be abvle to mod anything about 4.1.0". It doesnt, theres plenty of other guides which state you dont.

**Comment by shchmue** [comment]
the only thing i’m seeing is where it says you have to hard mod to coldboot, which means to do an “untethered” boot to payload facilitated by a modchip. it’s marked “optional”.

**Comment by Oscie57** [comment]
yeah i didnt notice the optional bit, my bad
